### ISSUE TITLE
No Gem support to identify SUN AWT Controls

### ISSUE THREAD

**Issue by duakalpana** [GraffitiResearchLabGermany/bombIR#114]
We have created framework to test Java thick client application using JRuby technology, but we are not able to identify those controls which are purely developed by SUN AWT. 

Gems which we used already:
activesupport (4.0.2)
addressable (2.3.5)
atomic (1.1.14 java)
bouncy-castle-java (1.5.0147)
builder (3.2.2)
childprocess (0.3.9)
columnize (0.3.6)
commonwatir (4.0.0)
ffi (1.9.3 java)
hoe (3.7.4)
httpclient (2.3.4.1)
i18n (0.6.9)
jdbc-mysql (5.1.28)
jruby-openssl (0.9.4, 0.9.3)
jruby-pageant (1.1.1 java)
jruby-win32ole (0.8.5)
json (1.8.0 java)
json_pure (1.8.1)
krypt (0.0.1)
krypt-core (0.0.1 universal-java)
krypt-provider-jdk (0.0.1)
libwebsocket (0.1.8)
lorax (0.2.0)
mini_portile (0.5.2)
minitest (4.7.5)
multi_json (1.8.4)
net-scp (1.1.2)
net-ssh (2.7.0)
nokogiri (1.6.1 java)
pkg-config (1.1.5)
rake (10.1.1, 10.1.0)
rautomation (0.13.0)
rdoc (4.0.1)
rr (1.1.2)
ruby-debug-base (0.10.4 java)
rubygems-update (2.2.1)
rubyzip (1.1.0)
selenium-webdriver (2.39.0)
sources (0.0.1)
test-unit (2.5.5)
test-unit-full (0.0.3)
thread_safe (0.1.3 java)
tzinfo (0.3.38)
watir (5.0.0)
watir-webdriver (0.6.6)
watir-webdriver-performance (0.2.3)
websocket (1.0.7)
win32-process (0.7.4)

Version of JRuby:
jRuby 1.7.10

Version Of JDK:
jdk1.7.0_45

Please give us pointer how to move ahead or what technology we need to apply for the same.

Thanks in advance

**Comment by SableRaf** [comment]
This does not seem relevant to the BombIR project.

**Comment by duakalpana** [comment]
It means can we say .. Via JRuby framework we can not identify Sun AWT Controls. And also please redirect me to concern person, if this is not relevant to this team.

Thanks in advance

**Comment by JesseScott** [comment]
Please refrain from commenting on this repo - we have nothing to do with JRuby or the AWT library...
