### ISSUE TITLE
Conflicting Architectures

### ISSUE THREAD

**Issue by JesseScott** [GraffitiResearchLabGermany/bombIR#27]
JavaCV Pro with GSVideo requires Processing to run in 64-bit mode.
PSMove requires Processing to run in 32-bit mode.

Rafa, can you recompile a 64bit version of your library ?

**Comment by JesseScott** [comment]
It seems that Windows and Linux can run the JavaCVPro library in 32 bit mode, but not OSX atm

**Comment by SableRaf** [comment]
I'm looking into it.

**Comment by JesseScott** [comment]
Ok. I've moved back to 32-bit and using the blobDetection library for the time being...

**Comment by SableRaf** [comment]
I tried to compile the lib as an universal binary. 
I'm not sure if it worked but you can try this one: http://s176381904.onlinehome.fr/autres/partage/psmove_processing_UB_2013_07_01.zip

**Comment by JesseScott** [comment]
No, didn't work.

**Comment by JesseScott** [comment]
this isn't urgent, and I seem to be getting along at 32-bits ok atm.
