### ISSUE TITLE
How Do I Draw ?

### ISSUE THREAD

**Issue by JesseScott** [GraffitiResearchLabGermany/bombIR#31]
hey guys... so getting close to passing the final XY location of the blob to the drawing engine, and I realize that I'm a little confused as to how that's going to work.

can someone please give me a quick rundown of how the psmove expects/accepts that positional data, and how I should pass it to it ?

**Comment by tugelbend** [comment]
Hey Jesse,
the psmove is not using the positional data at all. We currently only use it for transmitting button presses and for displaying the color. So setting the xy position in bombIR should be done independently of the psmove.
Cheers,

Hauke

**Comment by JesseScott** [comment]
Hmmm. Ok.
So, if we get a button press from the move, then call the spray function?
We don't seem to pass any positional data to that function... Let me wake
up and look at the code. Coffee first!

---

Jesse Scott

**Comment by tugelbend** [comment]
Good morning Jesse,
Right now the spray function in spraypaint.pde simply uses mouseX and mouseY values. If a psmove is connected it paints on the trigger button pressed, otherwise on left click.

**Comment by JesseScott** [comment]
Right. But the way the code is structured now, I don't see where/how it
paints when the move is connected...

---

Jesse Scott

**Comment by tugelbend** [comment]
That code is also in spraypaint.pde:

``` java
if (clicked == true || (moveConnected == false && mousePressed == true))
```

I tried to avoid to have too many if/else stuff in the bombIR draw function

**Comment by JesseScott** [comment]
I see that (and am just tracking down the 'clicked' boolean), but thats for when we are NOT using the move.

**Comment by JesseScott** [comment]
So as the code stands, we are painting at the mouse coordinates whether the move is connected or not... ? 
Is this placeholder code ?
Can I go ahead and change this ?

**Comment by tugelbend** [comment]
The 'clicked' var is set when using the psmove trigger button has been pressed. psmove.pde, line 45 ff:

``` java
if ( trigger > 0){
        clicked = true;
      } else {
        clicked = false;
      } 
```

**Comment by tugelbend** [comment]
Yeah, we are always using mouse coordinates. This can and should be changed.

**Comment by JesseScott** [comment]
I see that. But this is what we want to use when we are painting with the move, correct? The conditional, as it stands, is ambiguous in that it is evaluating to true in both cases...

**Comment by JesseScott** [comment]
Ok.

**Comment by tugelbend** [comment]
Yes, we use that when painting with the move. With no move connected that conditional won't be reached.

**Comment by JesseScott** [comment]
Right. But the conditional 
if (clicked == true || (moveConnected == false && mousePressed == true))
needs to be moved into two if's as it is covering both cases...

**Comment by tugelbend** [comment]
It evaluates to true if 'clicked' is true (which is the case, when the move trigger is pressed) OR it evaluates to true if no move is connected and the left mouse button is pressed. I don't see why this needs to be separated.

**Comment by JesseScott** [comment]
No. it evaluates to true if the move is connected and the trigger is pressed OR it evaluates to be true if the move is NOT connected and the mouse is pressed. 

So it needs to be separated because right now its ALWAYS evaluating to be true. Do we not want two separate cases - one for when the move is connected - in which case we are making it draw at the coordinates of the tracked IR blob - and another for when we are testing with the mouse...

**Comment by JesseScott** [comment]
This is what I've done to the spray() function: 

void spray() {
  // Setup the Shader
  ColorSlot activeCS = cs.getColorSlot(activeColorSlot);
  paintscreen.shader(pointShader, POINTS);

  depthOffset += offsetVel;

  //use the psmove trigger to change the weight of the spraypaint
  //pointShader.set( "weight", weight+trigger/5);
  pointShader.set( "refAngle", -1.0, 0.0 );
  pointShader.set( "weight", weight + random(0,20));
  pointShader.set( "dispersion", 0.2 );
  pointShader.set( "depthOffset", depthOffset );
  pointShader.set( "red", activeCS.getRed()/255);
  pointShader.set( "green", activeCS.getGreen()/255);
  pointShader.set( "blue", activeCS.getBlue()/255);
  //paintscreen.strokeWeight(weight+trigger/5);
  paintscreen.strokeWeight(weight + random(0,20));
  paintscreen.stroke(random(255), random(255), random(255)); 

  // spray when controller trigger is pressed
  if (moveConnected == true && clicked == true) {
    paintscreen.point(blobX, blobY);  
  }
  // if no controller present, spray on mouse click
  else if(moveConnected == false && mousePressed == true) {
    paintscreen.point(mouseX, mouseY);  
  }

}

**Comment by JesseScott** [comment]
The basic point I am trying to make is that we need to give it different coordinates than the mouseX/Y when the move is connected, since no one will be using the mouse at that point, and we will have blob coordinates to give it...

**Comment by SableRaf** [comment]
It looks fine.

**Comment by tugelbend** [comment]
I guess, I'm leaving discussion. My conditions are evaluating differently ;-)

**Comment by JesseScott** [comment]
Really ? 
But, do you understand my basic point? 
We dont want to pass the mouse coordinates to the state when the move is connected, but blob coordinates, right ?

**Comment by tugelbend** [comment]
Yes. I got that now. Currently the mouse coordinates are used all the time. And it's clear that we need to take the coordinates from the blob tracking when it's available instead of the mouse.
