### ISSUE TITLE
Camera Calibration: Crop area doesn't get bigger

### ISSUE THREAD

**Issue by tugelbend** [GraffitiResearchLabGermany/bombIR#33]
After scaling the crop area down using the calib menue, it's not possible to scale it up again.

**Comment by JesseScott** [comment]
Correct.
Can you live with a button that resets it to the original size? Its quite
tricky to rescale...

---

Jesse Scott

**Comment by SableRaf** [comment]
Crop behaviour fixed in merge https://github.com/GraffitiResearchLabGermany/bombIR/pull/37
