### ISSUE TITLE
gsvideo missing from Library folder

### ISSUE THREAD

**Issue by SableRaf** [GraffitiResearchLabGermany/bombIR#35]
By the way, shouldn't we be using Processing's native video library instead of gsvideo since they seem to be essentially the same thing?

**Comment by JesseScott** [comment]
I guess so...

**Comment by JesseScott** [comment]
Adding... it's quite big.

**Comment by JesseScott** [comment]
Added.

Also, tested with the native lib... sketch runs, but no blob detection ... looking into this..

**Comment by SableRaf** [comment]
Actually, they only seem to be the same because GSVideo follows the API of the built-in video library (I just found out). We can keep GSVideo since it works on all our machines now.

I also found this in the release notes for the 1.0 version:
`* Renamed some functions (play->start, pause->stop) in GSCapture.`
