### ISSUE TITLE
Cannot find anything named "sprayBrush"

### ISSUE THREAD

**Issue by tugelbend** [GraffitiResearchLabGermany/bombIR#40]
I tried to run the develop branch and got this error. spraypaint.pde, line 193. Had no time to look into the code for a more detailed bug report or fix.

**Comment by SableRaf** [comment]
I may have merged non working code by mistake while working on it. I'll be fixing this today along with a better PSMove implementation.

**Comment by tugelbend** [comment]
Newest version fixes it.
