### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by JesseScott** [GraffitiResearchLabGermany/bombIR#5]
I'm creating a /Libraries folder to store binaries of all the jars we're using, and I want to verify a few things...

a) We wont be using GLGraphics because we are using Processing 2.0
b) oscp5 v0.9.8
c) controlP5 v2.0.4
d) GML4U v. ??? 
e) Toxiclibs v.? (or as a dependency to GML4U ?)
f) SimpleOpenNi ??? really?
g) ProJMS ?

**Comment by tugelbend** [comment]
d) Yes. I would like to incorporate GML file loading/saving (latest version)
e) if we don't need it for GML4U then we don't 
g) Later. We might need it for an event in september (version 2)
h) keystone (version 4)
i) OpenCV (latest) ?

**Comment by JesseScott** [comment]
d) Yes, im just wonder which version - the latest ?

**Comment by tugelbend** [comment]
Hmm. Right. It's not the build that you can download at https://github.com/01010101/GML4U, I guess we need to build it ourselves from the sources. I will open an issue and ask Jerome to update the Readme file with a link to the location of the newest build.

**Comment by JesseScott** [comment]
But wait... we just need to load/save ? In that case, that build will work...
This isn't networked at all, right ?

**Comment by tugelbend** [comment]
Yeah, but the newest version does contain some other improvements i guess.

**Comment by JesseScott** [comment]
thats fine, it shouldnt break anything... lets assume we go with the latest and test.
