### ISSUE TITLE
CRITICAL: clicking on the already selected color button will cause crash

### ISSUE THREAD

**Issue by SableRaf** [GraffitiResearchLabGermany/bombIR#57]
`java.lang.ArrayIndexOutOfBoundsException: -1`

**Comment by tugelbend** [comment]
I will take care of that

**Comment by SableRaf** [comment]
More testing done and it only does it with the mouse, not with the can so it's less critical than I thought.

**Comment by SableRaf** [comment]
Related issue: https://github.com/GraffitiResearchLabGermany/bombIR/issues/59

**Comment by tugelbend** [comment]
This happens when a psmove is connected and a colorslot button is clicked that is already activated. With no move connected, no error.

**Comment by SableRaf** [comment]
Ok, we can live with that. Issue https://github.com/GraffitiResearchLabGermany/bombIR/issues/59 is actually more of a problem.

**Comment by tugelbend** [comment]
I'm on that

**Comment by SableRaf** [comment]
Fixed it temporarily doing this:

void radioButton(int a) {
if(a>=0) {
activeColorSlot = a;
}
}
