### ISSUE TITLE
Cannot select buttons or sliders with the can

### ISSUE THREAD

**Issue by SableRaf** [GraffitiResearchLabGermany/bombIR#59]

**Comment by tugelbend** [comment]
Hmm. This will be hard to fix tonight as the IR Can is in Lausanne. Let you know when I'm home if I can find a workaround for this.

**Comment by SableRaf** [comment]
It works with the color picker though. I suppose there is a difference between the way those two things are handled (the `pickColor()` function used blobX and blobY directly). Any pointers you can give me would be helpful.

**Comment by tugelbend** [comment]
I almost got the solution. Need 20 more minutes.

**Comment by tugelbend** [comment]
Bug is fixed. I will do the merge now.

**Comment by tugelbend** [comment]
Merge is not working. This will take a while. Github sucks sometimes.

**Comment by SableRaf** [comment]
When do you think you'll be done? Could I just add the changes to my code or is there too much stuff?

**Comment by tugelbend** [comment]
I am done. But the merge makes no sense. I added a robot. You did the same but somewhere else. So what do we do? Should I take care of that or will you do it? Doesn't make any sense to work at the same code if it's not clear who does what...

**Comment by tugelbend** [comment]
Again: Who should do the merge? Are you working on something now? I need some information, otherwise it's impossible to work from here.

**Comment by SableRaf** [comment]
I added a robot (for the cursor position only) and merged my last changes. You can make any modifications from there. Sorry for the wait.

**Comment by tugelbend** [comment]
Ok, so I will do the merge now.

**Comment by SableRaf** [comment]
We start setting up in 20 minutes. Do you think we'll have the merge by then?

**Comment by JesseScott** [comment]
I have to tweet that ;-) (sorry)

---

Jesse Scott

**Comment by tugelbend** [comment]
The merge is ready and pushed

**Comment by tugelbend** [comment]
Let me know if everything is working.

**Comment by SableRaf** [comment]
I still can't click on the buttons with the can, the difference is that, now, I can't pick the colors either.

**Comment by tugelbend** [comment]
check out the last version of my repo. I tested that and it worked on my computer

**Comment by SableRaf** [comment]
Can you merge it to develop?

**Comment by tugelbend** [comment]
thats what I did

**Comment by tugelbend** [comment]
there is no difference

**Comment by SableRaf** [comment]
Then I have your code and I can't click on anything with the can.

**Comment by tugelbend** [comment]
I don't get it. I have this code running here and it works fine with psmove and ir can. Did you make a complete fresh pull?

**Comment by SableRaf** [comment]
I will now.

**Comment by tugelbend** [comment]
I checked out the code again from the grl repo into an empty directory and it works

**Comment by SableRaf** [comment]
I switched move and it works. I blame it on bluetooth...

**Comment by tugelbend** [comment]
Great!

**Comment by SableRaf** [comment]
However, the robot mouse brought back this https://github.com/GraffitiResearchLabGermany/bombIR/issues/57

**Comment by tugelbend** [comment]
Ok, so let them use the spraycan button only for switching color slots. I will try to fix that bug in the meantime.

**Comment by SableRaf** [comment]
Fixed it temporarily doing this: 

void radioButton(int a) {
  if(a>=0) {
    activeColorSlot = a;
  }
}

**Comment by tugelbend** [comment]
Will you commit that?

**Comment by SableRaf** [comment]
Nope, it's a quick fix and may create other bugs.

**Comment by tugelbend** [comment]
Ok, so I won't provide a fix now.

**Comment by SableRaf** [comment]
No problem. We'll see how it goes tonight and make fine tuning tomorrow.
