### ISSUE TITLE
Processing 2.0

### ISSUE THREAD

**Issue by JesseScott** [GraffitiResearchLabGermany/bombIR#6]
Now that 2.0 is out of Beta, we should all be using it for this?
We should decide on 32-bit versus 64-bit as well (I think the video capture may have something to say on this...)

**Comment by SableRaf** [comment]
Since we're using PShader for the render, we have to use 2.0.
As for 32 vs 64, I don't know.

**Comment by JesseScott** [comment]
Ok, thought so. I was just curious about library compatibility, but if you check the /Libraries changes I made yesterday, it should be all good.

The one thing about 32 v 64 is that it changes the camera index from the Capture class, so we just need to decide on one. But certain JARs - ala OpenCV - may not work on 64... will test.

**Comment by tugelbend** [comment]
OpenCV works on 64 (at least on linux). A recompile of the processing
library is necessary though to make that one run. Described here:
http://www.zyztematik.org/?p=25

Didn't look for a Mac solution but guess that it's similar.

**Comment by JesseScott** [comment]
Ok... that's an old link, but it should work. I was looking more at this version though: http://codeanticode.wordpress.com/2011/11/21/opencv-2-in-processing/

**Comment by JesseScott** [comment]
This library works with video capture in 64bit mode for me...

**Comment by tugelbend** [comment]
Ah, ok. Didn't realize that the processing lib for OpenCV is outdated. The blob tracking and video capture examples of the old lib worked with OpenCV 2.4.5 on my machine. If we can't get JavaCV to work... ;-)
