### ISSUE TITLE
Mouse robot not working on second screens ?

### ISSUE THREAD

**Issue by SableRaf** [GraffitiResearchLabGermany/bombIR#66]
Cursor/Brush won't appear with the multi-screen setup.

This is marked resolved but I suspect that my version of Java still has the bug:  http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=5097723

**Comment by tugelbend** [comment]
So... is the installation running?

**Comment by SableRaf** [comment]
Nope.

**Comment by SableRaf** [comment]
blobX shows values like 1890.8683 to 1916.0543
blobY is about in the range of -66.41149 to -119.90509...

**Comment by tugelbend** [comment]
Fuck

**Comment by SableRaf** [comment]
That is after I removed the control from the robot. I don't get it. 
Maybe it's more something about the new calibration system for the blob values.

**Comment by tugelbend** [comment]
But can't you run the software without menu... better than nothing...

**Comment by SableRaf** [comment]
I don't have a working version at hand.

**Comment by SableRaf** [comment]
We decided to give up for tonight but use the evening to do more debugging on the real setup.

What's weird is the blob contours are drawn in the right place on the second screen. I have to check what is different in the way coordinates are passed to the spray manager.

**Comment by tugelbend** [comment]
That sounds like different problems to me. Is this all related to the robot problem or is there another problem...

**Comment by SableRaf** [comment]
It seems like another problem.

**Comment by SableRaf** [comment]
Opened new issue https://github.com/GraffitiResearchLabGermany/bombIR/issues/67

**Comment by tugelbend** [comment]
I got a fix for the mouse robot bug. Did you fix that already?

**Comment by SableRaf** [comment]
Not yet. Tell me.

**Comment by SableRaf** [comment]
Ok
