### ISSUE TITLE
Skipping calibration screen is not possible

### ISSUE THREAD

**Issue by tugelbend** [GraffitiResearchLabGermany/bombIR#82]
You can't skip calibration even if you don't want/need to do it (f.e. because using the mouse for painting)

**Comment by JesseScott** [comment]
Are you sure about this ?
I thought you could set it in the .properties ?

**Comment by SableRaf** [comment]
Actually, you can, but the tracking does not work when calib == false

**Comment by SableRaf** [comment]
This will be fixed by farming the calibration to a standalone module.
